- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
  # guides: [ Thieves ] # DS14: disabled due to lack of localization

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
    - ClothingHandsChameleonThief
